###
POST http://localhost:8000/api/datapostcpmk
Content-Type: application/json

{
    "id_cpmk": "132",
    "nama_cpmk": "Kemampuan Berpikir Kritis",
    "bobot_cpmk": "0.2",
    "id_cpl": "11002"
}


###
POST http://localhost:8000/api/login
content-type: application/json

{
    "email": "dany@students.undip.ac.id",
    "password": "dany1234"
}
###
POST http://localhost:8000/api/login
content-type: application/json

{
    "email": "arispujiwidodo@lecturer.undip.ac.id",
    "password": "aris1234"
}
###
POST http://localhost:8000/api/login
content-type: application/json

{
    "email": "operator@operator.undip.ac.id",
    "password": "operator1234"
}
###
POST http://localhost:8000/api/login
content-type: application/json

{
    "email": "if_departemen@departemen.undip.ac.id",
    "password": "departemen1234"
}
###
GET http://localhost:8000/api/dashboardmhs/getBobotCpl

###
GET http://localhost:8000/api/dashboardmhs/pencapaian?NIM=25000122410031&semester_mk=2
